title: Computational Ancient DNA Workshop
markdown: kramdown
remote_theme: alshedivat/al-folio
plugins:
  - jekyll-remote-theme
exclude:
  - requirements.txt
  - PROGRESS_NOTES.md
  - external_materials/
  - lectures/
  - .windsurfrules
