title: Computational Ancient DNA Workshop
markdown: kramdown
remote_theme: jekyll-theme-slate
exclude:
  - requirements.txt
  - PROGRESS_NOTES.md
  - external_materials/
  - lectures/
  - .windsurfrules
