version: '3.8'
services:
  jekyll:
    build: .
    command: jekyll serve --watch --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
